### PR TITLE
Remove `padding_left` setting to ensure all the plots have the same width

### PR DESCRIPTION
**Pull request by buhii**
This PR is to fix plot layout problem #2. In my environment, all plots will be displayed at the same width as the screenshot below.

Screen Shot 2023-04-19 at 11 17 56

### CODE REVIEW

**Review by timdiller — COMMENTED** [review]
Can you try to reduce the white space between the plots, too?  If possible, there would be only a minimal gap between the plots. It would be nice if it could work for up to five plots.

**Comment by buhii** [comment]
@timdiller 
Thanks for your advice! I adjusted the white space between the plots with https://github.com/timdiller/dynamic_plot_example/pull/4/commits/39e964216f88a63649441eed154883e0afd09a71. 

plot_39e9642

As far as I have tried, it seems that if the padding size of each plot is varied, the inner width of themselves also changes (this is a bit counter-intuitive for me). Therefore, I set the plot's padding to zero and the padding on the HPlotContainer itself. The disadvantage of this method is that the background color of the value_axis is not white (I set HPlotContainer's `bgcolor` to `"white"`, but it does not seem to apply to the padding.)

**Review by timdiller — APPROVED** [review]
Perfect!  This is what I was looking for.

**Comment by buhii** [comment]
@timdiller 
Thank you so much!

**Pull request merged**
