### PR TITLE
Add panning and zooming feature

### PR DESCRIPTION
**Pull request by kuromusha**
This PR is to add a feature mentioned on #3.

### CODE REVIEW

**Comment by timdiller** [comment]
I would like the plots to zoom along the "DEPTH" axis, that is the `value` or `y` axis.  Also, you should be able to connect the plots so that zooming one plot zooms all of them.

**Comment by kuromusha** [comment]
@timdiller 
Thank you for your comment. I changed the axis for the panning and zooming, and made the most left plot connect with the other plots for the panning and zooming.

**Comment by kuromusha** [comment]
I found the place to designate origin was wrong. I fixed that. (I noticed that because PanTool didn't work correctly.) https://github.com/timdiller/dynamic_plot_example/pull/9/commits/caf971701ceff1832a801843cba7a14631f0af0c

**Comment by timdiller** [comment]
LGTM

**Comment by timdiller** [comment]
FYI, in the description of your PR, you can include a line that says this
Closes #3 
and it should automatically close the issue when the PR is merged.  There should be some place in the github documentation that describes different kind of references you can make in PR and Issue descriptions.

**Pull request merged**
