### PR TITLE
Handle missing values

### LINKED ISSUE #1: Missing values are not properly handled
Screenshot 2023-04-18 at 19 45 14
It would appear that -999.25 is not being substituted for `np.nan` properly in `np.genfromtxt`.  Please fix.

### PR DESCRIPTION
**Pull request by kuromusha**
This PR is to fix #1. `numpy.genfromtxt()` has `missing_values` option, but it does not convert float values but only string values. So `data` has to be modified after calling `numpy.genfromtxt()`.

### CODE REVIEW

**Review by timdiller — CHANGES_REQUESTED** [review]
This will work, but please check the call signature for `genfromtxt` for a more-effective method.

**Comment by timdiller** [comment]
You can probably write a lambda function as a converter.

**Comment by kuromusha** [comment]
@timdiller 
Thank you for your comment. I changed to use `converters` parameter.

But not good things are that I have to prepare lambda functions for each column, and know the number of columns before designating `converters` parameter.

**Comment by kuromusha** [comment]
I reverted the `converters` change.

**Pull request merged**
